### ISSUE TITLE
[Feature Request] IOS Equalizer

### ISSUE THREAD

**Issue by b-risk** [dayanch96/YTMusicUltimate#104]
important feature yet to come to ios 
(source: https://www.reddit.com/r/YoutubeMusic/comments/phtne9/is_there_an_equalizer_in_youtube_music_or_youtube/ https://support.google.com/youtubemusic/thread/197361?hl=en&msgid=12565194 https://support.google.com/youtubemusic/thread/4339231/youtube-music-equalizer-option-on-ios-devices?hl=en )

**Comment by dayanch96** [comment]
Not easy to implement :)
