### ISSUE TITLE
Custom radio feature not working

### ISSUE THREAD

**Issue by ofer45600** [dayanch96/YTMusicUltimate#116]
You can select artists but you can’t proceed to actually make the radio it won’t proceed with creation…

**Comment by dayanch96** [comment]
Go to YTM settings and create it from there

**Comment by ofer45600** [comment]
Thanks man il try it!

**Comment by ofer45600** [comment]
Can’t seem to find the option in ytm settings

**Comment by dayanch96** [comment]
![5E7FA85E-0999-4B3B-B2E8-8950B28E9466](https://github.com/ginsudev/YTMusicUltimate/assets/38832025/7abf28dd-8224-4eb1-aaca-6b55d610ec5a)

**Comment by ofer45600** [comment]
Thanks for helping me bro!
But recommendations only teach the taste of music to the algorithm.. it doesn’t let you create a custom radio based on selected artists like the option on the homepage I’m referring to
![E7BCC10E-8370-4688-AA18-739BB746C47C](https://github.com/ginsudev/YTMusicUltimate/assets/65674886/639516ae-6007-4544-a146-de6e2c1b1ef2)

**Comment by dayanch96** [comment]
I'll take a look

**Comment by ofer45600** [comment]
You’re the best!

**Comment by dayanch96** [comment]
Hey @ofer45600 try it now. Tested on my devices and looks like it works - I see generated radio-playlists in me feed

https://github.com/dayanch96/YTMusicUltimate/releases/tag/v2.2

**Comment by ofer45600** [comment]
Hey thanks man!
Greatly appreciated

בתאריך יום ה׳, 19 בספט׳ 2024 ב-3:30 מאת Dan ***@***.***>:
