### ISSUE TITLE
[Feature Request] Lower Volume

### ISSUE THREAD

**Issue by AnhNangCuaEm** [dayanch96/YTMusicUltimate#117]
I've turned the volume to the lowest but it's still loud to me![image](https://github.com/ginsudev/YTMusicUltimate/assets/102863074/d6850e2e-6055-4ce1-b633-4192bceb6db3)![image](https://github.com/ginsudev/YTMusicUltimate/assets/102863074/8e1cf718-2e4d-4e61-99ac-9d1adc91d806)

**Comment by dayanch96** [comment]
Have you tried it on app from App Store?

**Comment by ginsudev** [comment]
Turn the volume down on your Bluetooth speaker?

**Comment by dayanch96** [comment]
> Does ur earphones have separate volume controls? Is it significantly loud? Or placebo?

I'm assuming it's an issue withsideloading or bluetooth speaker itself

**Comment by AnhNangCuaEm** [comment]
I think the audio source from youtube is already loud, I try at same volume level  with yt music on AppStore and amazon music in my screen record and amazon's volume is lower 
Video link (can't upload video here): https://drive.google.com/file/d/1cbgHQcng4SeVMHu4uldqSzlO19FBoNCn/view?usp=drivesdk

**Comment by AnhNangCuaEm** [comment]
Can you make it lower?🥺

**Comment by dayanch96** [comment]
So its app 'issue' and you asking for feature request?

**Comment by AnhNangCuaEm** [comment]
Sorry I didn't see where to write feature request😅
