### ISSUE TITLE
[Feature Request] Ability to change the File Name

### ISSUE THREAD

**Issue by arichornlover** [dayanch96/YTMusicUltimate#189]
Hey Dayanch96 or Ginsudev! I have a feature request for  YTMusicUltimate and it can be pretty useful!
Having the ability to change the file name.
and I actually have this video to showcase it!

https://github.com/ginsudev/YTMusicUltimate/assets/78001398/90b6f76a-8ca4-4c3c-8864-1efd9dbb44fa

and the source code I had made can be found in the url below!
https://github.com/arichornlover/YouTube-Reborn-v5/blob/eb53f645427280679e408a6c852a275b7f6cba47/Controllers/DownloadsAudioController.m#L179

and I didn’t want to make this a Pull Request, because I didn’t want to mess with your UISwipeActionsConfiguration in the Downloads Tab.

**Comment by dayanch96** [comment]
Hi. Thanks, i’ll take a look later today

**Comment by dayanch96** [comment]
@arichornlover which one you think is better?

textView:
https://github.com/dayanch96/YTMusicUltimate/assets/38832025/31753931-814c-48e8-a362-8eb27a8d0778

or textField:
https://github.com/dayanch96/YTMusicUltimate/assets/38832025/aced0b95-f40e-4c0c-99fd-d029face9dbe

**Comment by dayanch96** [comment]
Done
