### ISSUE TITLE
YouTubeultimate Download button goes missing after enabling force premium option

### ISSUE THREAD

**Issue by rockerz01** [dayanch96/YTMusicUltimate#193]

**Comment by dayanch96** [comment]
Tried on jailed and jailbroken states, both works with forced premium.

**Comment by rockerz01** [comment]
It showed first time after enabled force premium option after that it goes missing by its own.

**Comment by dayanch96** [comment]
still cant get this bug. make sure you're not doing something else

**Comment by PoomSmart** [comment]
I came across this issue. I believe what I did to fix it is as follows:
1. Disable YTMusicUltimate from the settings and apply changes (close YouTube Music app)
2. Launch the app again, there will be a premium upsell modal that you will click close button
3. Enable YTMusicUltimate from the settings again, apply changes and close the app
4. Launch the app again now with no issues

**Comment by dayanch96** [comment]
Should be fixed now with removed workaround
