### ISSUE TITLE
CarPlay Premium Support

### ISSUE THREAD

**Issue by ChipSkylark37** [dayanch96/YTMusicUltimate#20]
Though the App itself shows in CarPlay, upon opening it results in a message stating "Premium Subscription Required"

Is this something that could be fixed to allow the use of the App in CarPlay?

Interestingly, if you force close the app on your iPhone, CarPlay very briefly switches to display the top header as if it is working, but then immediately switches back to stating Premium is needed.

**Comment by ginsudev** [comment]
Thanks for letting me know. I'll look into it and see if I can improve CarPlay support

**Comment by ChipSkylark37** [comment]
Thanks - I even went so far as to build my own IPA with the App Store YTMusic and your 1.19 deb file which resulted in the same issue. So it may be some additional checks YT is doing to see if the account has Premium status, specifically when in CarPlay format. 

If you want to do any testing, I'd be happy to trial any builds.

**Comment by ChipSkylark37** [comment]
Hello. Have you been able to make any progress on this? If there's any way I could help, please let me know.

**Comment by ginsudev** [comment]
> Hello. Have you been able to make any progress on this? If there's any way I could help, please let me know.

Hi, I've just pushed v1.1.14 with some CarPlay patches. I'm unable to test but please let me know if that gets CarPlay working for you, cheers!

**Comment by ChipSkylark37** [comment]
Unfortunately it does not work - it goes to the same screen where it statues YouTube Music Premium is required. 

Are there logs locally on the phone that may assist?

**Comment by ginsudev** [comment]
> Unfortunately it does not work - it goes to the same screen where it statues YouTube Music Premium is required. 
> 
> Are there logs locally on the phone that may assist?

Not sure about logs, but I'll keep digging around YTMusic's code and see if I find anything interesting. I'll keep you updated

**Comment by c12n** [comment]
CarPlay may not work due to an entitlement issue and according to my understanding, CarPlay is not something that's possible with sil loaded apps without the use of a jailbreak

- SultanMods

**Comment by ChipSkylark37** [comment]
TrollStore is able to work with entitlements, such as CarPlay. This has been tested and validated with at least Spotify. Sorry for not mentioning that earlier.

**Comment by akarthik10** [comment]
I installed the tweak by injecting into original IPA and signed with required entitlements. My developer account is approved for carplay entitlement. Carplay app shows up, the playlist screen shows error saying a premium subscription is needed to use Carplay, but the "Now Playing" screen within the YTMusic Carplay app works well, I can go back/forward, pause, and set repeat. Album art shows up.

**Comment by ChipSkylark37** [comment]
That sounds very similar to when Spotify was not fully functional in CarPlay - You could see use it from the "Now Playing" section but not the app itself. 

However, since TrollStore / Developer Cert are allowed to use entitlements, this sounds more like YouTube has some other check to validate if you have YT Premium or hook. There is likely another hook that is checking this when it's loaded to CarPlay, where Spotify doesn't have that, or was patched. 

@ginsudev - Have you been able to find anything on this?

**Comment by ginsudev** [comment]
Yeah I've made progress on CarPlay support. However what I have currently is still not enough to get it in a functional state. I'll continue digging into it but it's hard to test because I don't actually have a CarPlay car :(

**Comment by ChipSkylark37** [comment]
Is there anything that we can do to assist testing?

**Comment by akarthik10** [comment]
Carplay simulator might be useful: https://developer.apple.com/documentation/carplay/using_the_carplay_simulator

**Comment by supperball** [comment]
thank you verry much, I finding too youtube work in carplay without jailbreak

**Comment by subasically** [comment]
Thanks for looking into this! 
I am also unable to use CarPlay.

**Comment by m4xolotl** [comment]
Any fixes? YTMusicUltimate isn't even showing up on my Carplay!

I have a developer account

**Comment by gowthamravichandran** [comment]
> Yeah I've made progress on CarPlay support. However what I have currently is still not enough to get it in a functional state. I'll continue digging into it but it's hard to test because I don't actually have a CarPlay car :(

Hey @ginsudev, I have a carplay car, I can help test through multiple cycles. let me know what you need to me to do!

**Comment by ceedveed** [comment]
I am also looking for CarPlay support. I use TrollStore, so the CarPlay entitlements will work.

**Comment by dayanch96** [comment]
Since we don’t have CarPlay and this feature has not been added for few years, closing this issue as not planned due to the impossibility of completing

**Comment by dayanch96** [comment]
Not sure if it works, but got feedback that 2.2 does work on CarPlay now

**Comment by Tomasruscelli** [comment]
> Not sure if it works, but got feedback that 2.2 does work on CarPlay now

On what version of ytmusic? Injectet in original AppStore or sideloaded trought TrollStore?
My 2.2 injected doesn’t work

**Comment by Fannangir** [comment]
Just see this thread.
Sorry for opening 309.
Is there enhancement really closed?

**Comment by wojtoosh** [comment]
Without CarPlay all idea of YTMusic has no sense

**Comment by alma359** [comment]
With a paid Apple developer account and CarPlay entitlements the app becomes visible in CarPlay and opens, however library section has the playlists from my account missing. Seems like my account is not signed in, but it is on the iPhone. Is there a solution for this?
