### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by VioletTides** [dayanch96/YTMusicUltimate#232]
When I try to sign in using this, there is an error message from google that reads: "You can't sign in to this app because Google can't confirm that it's safe."

I am on IOS 17.4 and have tried multiple .deb versions and .ipa versions with no success.

**Comment by VioletTides** [comment]
I should add that I was able to create a new account and get inside the app, but I am still unable to switch accounts inside the app as it gives the same error unfortunately. I have tried the #115 solution but was unable to find success with it either. For reference I am using YouTubeMusicUltimate v2.0.4 with YouTube Music ipa 6.43

**Comment by dayanch96** [comment]
you dont have to. just try to sign in, close signing window and try again

**Comment by VioletTides** [comment]
Hi, thanks for the reply. It doesn't seem to work for me. I am pressing the cancel button to close the sign in window. Is that what is meant? Here is a video of me trying it. Thank you for your help.

https://github.com/ginsudev/YTMusicUltimate/assets/81711759/31a6949f-9b1e-4c56-8d3e-6f70a9ec1289

**Comment by VioletTides** [comment]
Another update. After sleeping I opened the app again, only to find I was signed out of the new account I made. Still stuck at login and I have tried the other solutions contributors commented below #115 to no avail.

**Comment by dayanch96** [comment]
Second acc signing in does’t work for now. Already fixed though. Testing, will upload soon

**Comment by dayanch96** [comment]
Fixed. Try using latest release: https://github.com/dayanch96/YTMusicUltimate/releases/tag/v2.0.5
