### ISSUE TITLE
deb to ipa

### ISSUE THREAD

**Issue by khukd12** [dayanch96/YTMusicUltimate#234]
Sorry I don't know anything about how to do this. I've been just downloading ipa my whole life. Can anyone help me on how to create an ipa file using the github actions? I have no clue.

**Comment by dayanch96** [comment]
Here is tutorial: https://github.com/ginsudev/YTMusicUltimate#how-to-build-the-package-by-yourself-on-your-device

**Comment by 3rdQuasar** [comment]
> Here is tutorial: https://github.com/ginsudev/YTMusicUltimate#how-to-build-the-package-by-yourself-on-your-device

Only on PC?

**Comment by dayanch96** [comment]
any device. as long aa you have direct link to ipa file

**Comment by 3rdQuasar** [comment]
Another question how does lyrics test selection work,just hold press on lyrics? If that is the method it seems don't work

**Comment by khukd12** [comment]
> any device. as long aa you have direct link to ipa file

Hi, this is where I am confused about. It asks for the ipa file url, which I cannot find. Am I supposed to go through something to create a url?

**Comment by 3rdQuasar** [comment]
yes
you can use dropbox
> > any device. as long aa you have direct link to ipa file
> 
> 
> 
> Hi, this is where I am confused about. It asks for the ipa file url, which I cannot find. Am I supposed to go through something to create a url?

**Comment by mustafacakirogludev** [comment]
> > any device. as long aa you have direct link to ipa file
> 
> 
> 
> Hi, this is where I am confused about. It asks for the ipa file url, which I cannot find. Am I supposed to go through something to create a url?


You need to somehow find a decrypted YTMusic ipa(google is your friend), upload it to Dropbox, put that dropbox url to the necessary field. Sorry but unless you want Google to take down the whole project, this is the best we can do.

**Comment by khukd12** [comment]
> > > any device. as long aa you have direct link to ipa file
> > 
> > 
> > Hi, this is where I am confused about. It asks for the ipa file url, which I cannot find. Am I supposed to go through something to create a url?
> 
> You need to somehow find a decrypted YTMusic ipa, upload it to Dropbox, put that dropbox url to the necessary field. IPA itself is a property of Google and we cannot provide it without getting sued. We are just here to provide a useful tweak, not to share copyrighted property.

Ah, I see. Thank you so much. I will try to figure it out.

**Comment by dayanch96** [comment]
hey, have you figured out? @khukd12

**Comment by khukd12** [comment]
> hey, have you figured out? @khukd12

Sadly, no.

**Comment by dayanch96** [comment]
> Sadly, no.

You need decrypted IPA file (Google it). Download IPA file and upload it to anywhere you will have a direct link to the file (i.e. dropbox). This link will be needed in Github actions.
