### ISSUE TITLE
YouTube music Version For Latest Update

### ISSUE THREAD

**Issue by JustAiden9** [dayanch96/YTMusicUltimate#241]
What YouTube music version should I use with the injected deb?

**Comment by dayanch96** [comment]
any

**Comment by JustAiden9** [comment]
> any

That's not true, when I use the latest version on a non-jailbroken iPhone with the injected tweak I can't sign in...

**Comment by dayanch96** [comment]
https://github.com/dayanch96/YTMusicUltimate/issues/115

**Comment by JustAiden9** [comment]
> https://github.com/dayanch96/YTMusicUltimate/issues/115

Well the newest YouTube Music Version I try to use does not work with that method for some reason. It opens a window but not a safari window. It's like a custom window.

**Comment by JustAiden9** [comment]
![image](https://github.com/dayanch96/YTMusicUltimate/assets/104693998/422190bf-a350-4fbb-812d-da0798c71c3d)

Btw here is what the updated 6.44.3 YT music looks like.
