### ISSUE TITLE
App crashing after trying to login

### ISSUE THREAD

**Issue by ggvick** [dayanch96/YTMusicUltimate#247]
### Describe the bug

```yaml
Once I first load the app for the first time, it asks me would you like to enable the force premium option and I click cancel, I also tried clicking yes after reinstalling but it does nothing. Once I click the sign in button it asks if you would like to use google.com to sign in, I click continue and the app crashes. I have tried to re-install the app many times but it does nothing.

I am using a iphone 15 pro max on iOS 17.4, The app is installed with sidestore.
```

### Steps to reproduce

```yaml
1. install the app
2. click cancel on the force enable premium
3. click sign in
4. click continue on the popup "youtube music would like to use google.com to sign in"
5. the app crashes
```

### Crashlog

I can't since I cannot get past the login screen.

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Fixed. Thanks for the report
