### ISSUE TITLE
Can't sign in because google can't confirm its safe

### ISSUE THREAD

**Issue by Liquidrag** [dayanch96/YTMusicUltimate#248]
### Describe the bug

```yaml
Can't sign in because google can't confirm its safe.


I used sideloadly to inject the com.ginsu.ytmusicultimate_2.0.6_iphoneos-arm64.deb into a 6.45 decrypted ipa 

installed and get not safe error

I want to use sideloadly so I can have the ipa to install automatically weekly for convenience.
```

### Steps to reproduce

```yaml
1. put in email to log in
2. get not safe error
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey, make sure you have not injected tweak from releases page since it meant to be used on jailbroken devices and does not contain sideloading.xm.

Instead, make package using
`make clean package SIDELOADING=1`

**Comment by Liquidrag** [comment]
> Instead, make package using
> `make clean package SIDELOADING=1`

I’m not sure how to do that. Is there a tutorial for this?

**Comment by dayanch96** [comment]
https://github.com/dayanch96/YTMusicUltimate?tab=readme-ov-file#how-to-build-the-package-by-yourself-on-your-device

**Comment by thaibm92** [comment]
Localization is not working, please check it for me
