### ISSUE TITLE
Clearly mention supported Youtube base version in the release notes 

### ISSUE THREAD

**Issue by Saud-97** [dayanch96/YTMusicUltimate#249]
### Describe the feature request

```yaml
Clearly mention Youtube base version number (so we can know which version of decrypted YTMusic .ipa to use) in the release notes which users should use to inject the tweak for sideloading
```
Since there will be issues/crashes when an unsupported or outdated version used.

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey @Saud-97 , thanks for the request! Have ever happen to you that tweak crashed with oldest ytm versions?

**Comment by dayanch96** [comment]
I've been working on this tweak for few years and haven't encountered a such problem yet.

It's better to use the latest version of the tweak. But ytm version up to users

**Comment by Saud-97** [comment]
So am I safe to always use latest version of ytm with the tweak? If thats the case then no worries.

I just thought after few months there could be issues raising because of how different the new vs old tweaks compatibility.  But I think its clear now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
