### ISSUE TITLE
Localization doesn't work

### ISSUE THREAD

**Issue by thaibm92** [dayanch96/YTMusicUltimate#250]
### Describe the bug

```yaml
As the title describes, localization doesn't work on version v2.0.6 - IPA 6.45.4, I use your .deb release
```

### Steps to reproduce

```yaml
Inject .deb from https://github.com/dayanch96/YTMusicUltimate/releases/tag/v2.0.6
```

### Crashlog

![z5314714793953_774283de29638c707e211852ffd9e54d](https://github.com/dayanch96/YTMusicUltimate/assets/68208369/6f902d5f-1501-4909-8f61-d849f4425f2a)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Done. Try again
