### ISSUE TITLE
Unlimited music listening by disabling "You There" controller

### ISSUE THREAD

**Issue by PoomSmart** [dayanch96/YTMusicUltimate#254]
### Describe the feature request

Just like [YouAreThere](https://github.com/PoomSmart/YouAreThere) tweak for iOS YouTube app, I may plan to create a pull request. However, in case you are more ready to implement, here are the hooks:

```
%hook YTColdConfig

- (BOOL)enableYouthereCommandsOnIos { return NO; }

%end

%hook YTYouThereController

- (BOOL)shouldShowYouTherePrompt { return NO; }

%end
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey, thanks. How does it work? Prohibits interrupting playback with the "You There" notification?

**Comment by PoomSmart** [comment]
Yes, however as I checked again this feature seems to be off by default now..(?)

**Comment by dayanch96** [comment]
Both off on my device. Guess we can add it as option to enable

**Comment by dayanch96** [comment]
Turns out that YT and YTM sets some AB features only once at first startup, so I added it by default now. Thanks
