### ISSUE TITLE
Lyrics button disappeared???

### ISSUE THREAD

**Issue by Altex2** [dayanch96/YTMusicUltimate#260]
### Describe the bug

```yaml
I don’t seem to find a setting to disable lyrics but somehow i disabled them?
```

### Steps to reproduce

```yaml
I have no ideea exactly
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Disable Force premium option in tweak settings
