### ISSUE TITLE
Lyrics button is missing

### ISSUE THREAD

**Issue by anselmo-carvalho** [dayanch96/YTMusicUltimate#262]
### Describe the bug

```yaml
YouTube Music Ultimate v.2.0.7 is not showing the LYRICS button at the bottom of the screen, between UP NEXT and RELATED. 
Will there be a fix?
Thanks!
```

### Steps to reproduce

```yaml
I played a music using the original app and it showed the button LYRICS and there it was.
The same song in YTUltimate doesn't show the LYRICS button.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Hey! Thanks for the issue. It happens only when You enable 'Force enable premium' option under Premium options section. If you don't have playback issues, it is recommended to disable this option

**Comment by anselmo-carvalho** [comment]
You are right: I disabled it and now the lyrics is working.
Thanks Dan.
