### ISSUE TITLE
partial color change in oled theme

### ISSUE THREAD

**Issue by playergamespro** [dayanch96/YTMusicUltimate#264]
### Describe the bug

```yaml
The color of the album surrounding the song is partially black in up next in the oled theme
```

### Steps to reproduce

```yaml
1. Choose a song of liking.
2. Go to Up Next or one of the tabs below.
3. The color of the album surrounding is partially black.
```

### Crashlog

https://github.com/dayanch96/YTMusicUltimate/assets/110026501/568aef27-84f5-47ba-8dbc-3d4cfccf6066

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Fixed
