### ISSUE TITLE
Cannot Remove the subscription to premium button for version 7.01 and higher

### ISSUE THREAD

**Issue by thaibm92** [dayanch96/YTMusicUltimate#265]
### Describe the bug

```yaml
As the title mentioned, it seems that Google is changing the code that displays the Premium version and your teawk cannot Remove the subscription to premium button. can you fix it, thank you very much
```

### Steps to reproduce

```yaml
open app-> go Logo account
```

### Crashlog

![z5471589797075_84a782e131acef0ae37bba644a07df3d](https://github.com/dayanch96/YTMusicUltimate/assets/68208369/4ed4790a-45f9-441a-a56f-a448f57b80d8)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [X] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Fixed.

@thaibm92 please read carefully template next time before marking all checkboxes.
