### ISSUE TITLE
Add `YouTube Fix` tweak to load avatars

### ISSUE THREAD

**Issue by rakleed** [dayanch96/YTMusicUltimate#266]
### Describe the feature request

Could you please add https://github.com/whoeevee/YouTube-Fix tweak? In some countries, the `yt3.ggpht.com` domain is blocked, which is why channel avatars are not loaded, and this tweak simply replaces the domain with `yt4.ggpht.com`. This is more relevant for the YouTube app, but in YouTube Music avatars are also not visible in comments.

<details><summary>Screenshot</summary>

![YTMusicUltimate avatars not loading](https://github.com/dayanch96/YTMusicUltimate/assets/19418601/e5bba395-cdfe-4d50-8783-65ca7256ab78)

</details>

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Inject it manually

**Comment by Jazooxd** [comment]
> How?

Build with theos but i make it and [here](https://gofile.io/d/eVrCvW) is it.
