### ISSUE TITLE
Music playback stops

### ISSUE THREAD

**Issue by Kaspeck** [dayanch96/YTMusicUltimate#268]
### Describe the bug

```yaml
Downloaded music playback stops ~30 seconds after turning off my phone screen. The app doesn’t crash and resumes music after pressing play. In another ~30ish seconds it pauses again.
```

### Steps to reproduce

```yaml
1. Download a song
2. Play the song
3. Turn off your phone screen
4. Wait 30 seconds
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Make sure you don't have anything conflicting (other apps that playing in BG, etc.) with the player.
