### ISSUE TITLE
Building IPA is going wrong

### ISSUE THREAD

**Issue by Corotyest** [dayanch96/YTMusicUltimate#269]
### Describe the bug

```yaml
All the steps further to the package making was going great
```

### Steps to reproduce

```yaml
until this 

YTMusicUltimate % make clean package
Makefile:13: /makefiles/common.mk: No such file or directory
Makefile:26: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.
```
```


### Crashlog

_No response_

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
make sure your theos installed correctly

**Comment by chwhaanews** [comment]
Run git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
fatal: could not read Username for 'https://github.com/': Device not configured
Error: Process completed with exit code 128.

**Comment by chwhaanews** [comment]
![福昕截屏20240702154924295](https://github.com/dayanch96/YTMusicUltimate/assets/31620868/2c0afdae-5625-4f94-b9c5-9f3a513cdff2)

**Comment by MrAlucardDante** [comment]
I opened a pull request that fixes the issue. In the mean time, everyone that forked the project can update their workflow file as I did until the pull request is merged https://github.com/dayanch96/YTMusicUltimate/pull/272

**Comment by chwhaanews** [comment]
problem resolved

**Comment by Velocity07** [comment]
Any updates on when arichorn 's account will be re-instated or if there is an alternative way to get the SDK's?

**Comment by zSynt3x** [comment]
> Any updates on when arichorn 's account will be re-instated or if there is an alternative way to get the SDK's?

Just change the SDK target with the one fixed. Or try to copy/sync the public repo from @MrAlucardDante

**Comment by zSynt3x** [comment]
> Any updates on when arichorn 's account will be re-instated or if there is an alternative way to get the SDK's?

Just change the SDK target with the one provided. Or try to copy/sync the public repo from @MrAlucardDante

**Comment by chwhaanews** [comment]
![Screenshot_2024-07-19-12-17-33-767_com.github.android-edit.jpg](https://github.com/user-attachments/assets/492f5a82-6bed-40f5-8ff2-cca644112472)

modify code like this, then it works.

**Comment by Blockr22** [comment]
Run brew install coreutils
  
==> Downloading https://ghcr.io/v2/homebrew/core/coreutils/manifests/9.5-1
==> Fetching coreutils
==> Downloading https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:0177633e7a1b426030d1172b7237c765f96be4ef54c4e455f99fc65ff3d60119
==> Pouring coreutils--9.5.monterey.bottle.1.tar.gz
==> Caveats
Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
==> Summary
🍺  /usr/local/Cellar/coreutils/9.5: 4[8](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:8)1 files, 14.2MB
[*] Downloading CydiaSubstrate.framework...
[*] Downloading Substitute...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 7213k    1 [8](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:9)1280    0     0   230k      0  0:00:31 --:--:--  0:00:31  230k
  2 2475k    2 677[9](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:10)2    0     0   192k      0  0:00:12 --:--:--  0:00:12  191k
 56 2475k   56 1401k    0     0  [10](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:11)59k      0  0:00:02  0:00:01  0:00:01 1058k
 20 7213k   20 1474k    0     0  [11](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:12)10k      0  0:00:06  0:00:01  0:00:05 1110k
100 2475k  100 2475k    0     0  [12](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:13)49k      0  0:00:01  0:00:01 --:--:-- 1249k
[*] Downloaded CydiaSubstrate.framework
 43 72[13](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:14)k   43 3163k    0     0  1328k      0  0:00:05  0:00:02  0:00:03 1328k
 64 7213k   64 4677k    0     0  1385k      0  0:00:05  0:00:03  0:00:02 1385k
 92 7213k   92 6685k    0     0  1529k      0  0:00:04  0:00:04 --:--:-- [15](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:16)29k
100 7213k  100 7213k    0     0  1574k      0  0:00:04  0:00:04 --:--:-- [16](https://github.com/Blockr22/YTMusicUltimate/actions/runs/10126725370/job/28003712050#step:13:17)83k
[*] Downloaded Substitute
[/Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa or
        /Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa.zip, and cannot find /Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa.ZIP, period.
[/Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa or
        /Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa.zip, and cannot find /Users/runner/work/YTMusicUltimate/YTMusicUltimate/main/YouTubeMusic.ipa.ZIP, period.
[*] Couldn't set app executable
Error: Process completed with exit code 12.

**Comment by NilUx98** [comment]
same issue
Error: Process completed with exit code 12.
![image](https://github.com/user-attachments/assets/273869d9-2ee0-4396-9684-30c4e64afb4e)

**Comment by mustafacakirogludev** [comment]
Please update your forks, we just pushed a commit fixing this issue.
