### ISSUE TITLE
Forked project Build Error: Process completed with exit code 128 

### ISSUE THREAD

**Issue by santhosh-D-subramani** [dayanch96/YTMusicUltimate#271]
### Describe the bug

```yaml
getting error on build
fatal: could not read Username for 'https://github.com': Device not configured
Error: Process completed with exit code 128.
```

### Steps to reproduce

```yaml
1. forked repo
2. found a decrypted.iPA(com.google.ios.youtubemusic_7.04_und3fined) started build as per instructions in github actions
3. Error: Process completed with exit code 128.
```

### Crashlog

```
X Download IOS SDK: 
Run git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
  git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
  cd sdks
  git sparse-checkout set --no-cone iPhoneOS16.2.sdk
  git checkout
  mv *.sdk $THEOS/sdks
  shell: /bin/bash -e {0}
  env:
    THEOS: /Users/runner/work/YTMusicUltimate/YTMusicUltimate/theos
fatal: could not read Username for 'https://github.com': Device not configured
Error: Process completed with exit code 128.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by jbails5** [comment]
what was the fix?

**Comment by mustafacakirogludev** [comment]
@jbails5 if you are still having problems, I just pushed a fix. Please try again.
