### ISSUE TITLE
Option to choose audio quality Download

### ISSUE THREAD

**Issue by Xellerate005** [dayanch96/YTMusicUltimate#279]
### Describe the feature request

```yaml
An option in the settings possibly underneath the download option, or if you click the download option it takes you to another setting that enables to choice of audio qualities, right now the audio quality of downloaded songs are garbage, and for some reason sound better in VLC than any music app on iOS.
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
There is no plans for that. YTM provides only Normal and bad quality
