### ISSUE TITLE
Popup Ads Premium appears occasionally

### ISSUE THREAD

**Issue by thaibm92** [dayanch96/YTMusicUltimate#284]
### Describe the bug

```yaml
As the title says, when opening the app, sometimes premium ads pop up, I found it appears from version 7.12.3 later
```

### Steps to reproduce

```yaml
Open YouTube Music app -> see popup ads
```

### See Popup ads

![image](https://github.com/user-attachments/assets/74462d03-3036-470f-95d7-301cad28fd07)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
Should be fixed now. https://github.com/dayanch96/YTMusicUltimate/releases/tag/v2.2
