### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by gehir** [dayanch96/YTMusicUltimate#294]
### Describe the bug

```yaml
[!] YouTubeMusic.ipa is not a zipfile (ipa)
[*] extracting ipa..
[*] deleting temporary directory..
Error: Process completed with exit code 1.

I don't know why this is happening but there's no info. I tried linking a zipped ipa and it still says its not a zipfile so... I don't know what to do. I can't find the discord for support. I will do this on my machine instead, but for future users please fix.
```

### Steps to reproduce

```yaml
Run the workflow using the steps he wrote
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
use direct link to the ipa file

**Comment by gehir** [comment]
i was though. i uploaded it to filebin and copied the link. nothing else to say. it simply won't work. not sure why

**Comment by dayanch96** [comment]
Direct link to the **ipa**. not `rar`, `zip` or anything else

![IMG_9601](https://github.com/user-attachments/assets/7b559e76-7fb4-4ded-97c4-034e4f3b6464)

**Comment by gehir** [comment]
alright let me run it again and ill confirm that it downloads a .ipa from my link and i'll see if its resolved for some reason.

**Comment by dayanch96** [comment]
This link also incorrect. You have to put the link that lets you directly download ipa file. Try dropbox. Spend some time on reading readme

![Uploading IMG_9602.jpeg…]()

**Comment by gehir** [comment]
sorry, i'm not sure how this happened but i literally did the same thing right now and it worked. uploaded to litterbox, copied the link, and now it works fine. the first time i did it i uploaded the .ipa file, copied the link and got that error. maybe its just a weird error. i should have tried it more than just once.
