### ISSUE TITLE
YTMUltimate downlpad button disappeared

### ISSUE THREAD

**Issue by MohaBars** [dayanch96/YTMusicUltimate#296]
### Describe the bug

```yaml
The YTMUltimate button (the one in the player that is used to download the audio or the cover image) disappeared after closing the app and reopening. Tested on both a jailbroken device and non jailbroken and still got the same issue. 

I tested toggling ytmultimate off from the settings and re-enabling. I also tested toggling the download audio and download cover image on and off and the issue persisted.
```

### Steps to reproduce

```yaml
1. Open player and button is there. 
2. Quit app completely by swiping it up from the open applications. 
3. Reopen app 
4. Open player and button is not there.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [X] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by ERROR4051987** [comment]
i was able to fix this for myself by:
1. downgrading youtube music to V701.5
2. disabling YTMusicUltimate button and restarting the app 
3. reenabling YTMusicUltimate button and restarting the app

**Comment by dayanch96** [comment]
Fixed. Try using latest release
