### ISSUE TITLE
Switch Between Video and Music

### ISSUE THREAD

**Issue by BathiyaRanasinghe** [dayanch96/YTMusicUltimate#307]
### Describe the feature request

```yaml
Is it possible to add in the premium feature to seamlessly switch between the music video and the music. 


Would be nice to have
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by BathiyaRanasinghe** [comment]
![IMG_A1830C71F6C2-1](https://github.com/user-attachments/assets/38b96a1d-a823-4e72-9da0-f59e133b1954)
AS shown here

**Comment by dayanch96** [comment]
it is already impemented
