### ISSUE TITLE
CarPlay support

### ISSUE THREAD

**Issue by Fannangir** [dayanch96/YTMusicUltimate#309]
### Describe the feature request

```yaml
I don’t see the application in the car when connected via CarPlay.
Should I see it or am I missing something?
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by OffPS** [comment]
Same here! Is there any solution?

**Comment by dayanch96** [comment]
#20
