### ISSUE TITLE
Downloaded Music

### ISSUE THREAD

**Issue by OffPS** [dayanch96/YTMusicUltimate#310]
### Describe the bug

```yaml
It only reproduce one song when I have 10 downloaded songs. It does not go to the next song.

Also, the library cannot be downloaded.
```

### Steps to reproduce

```yaml
1. Download several songs
2. Reproduce the first one
3. Then it will not reproduce the next song.
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I have read the 'IPA Building Troubleshooting' section (Only for issues related to building the IPA file).
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by dayanch96** [comment]
It’s not a bug. There no queue feature
